export const SET_CAMPAIGN_NAME = 'SET_CAMPAIGN_NAME';

export const SET_CAMPAIGN_DESCRIPE = 'SET_CAMPAIGN_DESCRIPE';

export const ADD_SUBCAMPAIGN = 'ADD_SUBCAMPAIGN';

export const SET_SUBCAMPAIGN_NAME = 'SET_ADD_SUBCAMPAIGN_NAME';

export const SET_SUBCAMPAIGN_STATUS = 'SET_SUBCAMPAIGN_STATUS';

export const ADD_ADV = 'ADD_ADV';

export const SET_ADV_NAME = 'SET_ADV_NAME';

export const SET_ADV_QUANTITY = 'SET_ADV_QUANTITY';

export const DELETE_ADS = 'DELETE_ADS';
